tech_blog:
    resource: "@TechBlogBundle/Resources/config/routing.yml"
    prefix:   /

sum:
    resource: "@TechBlogBundle/Controller/SumController.php"
    type: annotation
    prefix: /prefix

register_author:
    path: /register-author
    defaults: { _controller: TechBlogBundle:Author:register }

security_login:
    path: /login
    defaults: { _controller: TechBlogBundle:Security:login }

security_logout:
    path: /logout