tech_blog:
    resource: "@TechBlogBundle/Resources/config/routing.yml"
    prefix:   /

sum:
    resource: "@TechBlogBundle/Controller/SumController.php"
    type: annotation
    prefix: /prefix

logout:
    path: /logout
