# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        tech_users:
            entity: { class: TechBlogBundle\Entity\Author, property: nickname }

    encoders:
        TechBlogBundle\Entity\Author: bcrypt


    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - TechBlogBundle\Security\LoginFormAuthenticator
            logout:
                path: /logout


    access_control:
        - { path: ^/post, roles: ROLE_USER }
