security:

    providers:
        tech_users:
            entity: { class: TechBlogBundle\Entity\Author, property: nickname }
    encoders:
        TechBlogBundle\Entity\Author: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: ~
            anonymous: ~
            guard:
                authenticators:
                    - TechBlogBundle\Security\LoginFormAuthenticator
            logout:
                path: /logout

    access_control:
        - { path: ^/add-post, roles: ROLE_USER }
#        - { path: ^/edit-post, roles: ROLE_USER }
#        - { path: ^/remove-post, roles: ROLE_USER }

    role_hierarchy:
        ROLE_SUPERADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]