tech_blog_homepage:
    path:     /
    defaults: { _controller: TechBlogBundle:Default:index }

show_date:
    path: /date
    defaults: { _controller: TechBlogBundle:Default:showDate }

hello_user:
    path: /hello/{name}/{lastName}
    defaults: { _controller: TechBlogBundle:Default:helloUser , name: 'Yaml', lastName: 'PHP'}
    requirements:
        lastName: '\D+'

tech_blog_invoke:
    path:     /invoke
    defaults: { _controller: TechBlogBundle\Controller\DefaultController }
