tech_blog_homepage:
    path: /
    defaults: { _controller: TechBlogBundle:Default:index }

category:
    path: /category/{slug}
    defaults: { _controller: TechBlogBundle:Default:showByCategory }
    requirements:
        slug: '\D+'

show_post:
    path: /post/{slug}
    defaults: { _controller: TechBlogBundle:Default:showPost }
#    requirements:
#        slug: '\D+'




